
(function(){var f=null;function k(a){this.t={};this.tick=function(a,c,d){d=d?d:(new Date).getTime();this.t[a]=[d,c]};this.tick("start",f,a)}var l=new k;window.GA_jstiming={Timer:k,load:l};if(window.GA_jstiming){window.GA_jstiming.d={};window.GA_jstiming.i=1;var m=function(a,b,c){var d=a.t[b],e=a.t.start;if(d&&(e||c))return d=a.t[b][0],e=c!=void 0?c:e[0],d-e};window.GA_jstiming.report=function(a,b,c){var d="";a.h&&(d+="&"+a.h);var e=a.t,h=e.start,j=[],o=[],g;for(g in e)if(g!="start"&&g.indexOf("_")!=0){var p=e[g][1];p?e[p]&&o.push(g+"."+m(a,g,e[p][0])):h&&j.push(g+"."+m(a,g))}delete e.start;if(b)for(var s in b)d+="&"+s+"="+b[s];var a=[c?c:"http://csi.gstatic.com/csi","?v=3","&s="+(window.GA_jstiming.sn||
"gam")+"&action=",a.name,o.length?"&it="+o.join(","):"","",d,"&rt=",j.join(",")].join(""),b=new Image,i=window.GA_jstiming.i++;window.GA_jstiming.d[i]=b;b.onload=b.onerror=function(){delete window.GA_jstiming.d[i]};b.src=a;b=f;return a}};var n=this,q=function(a,b){var c,d=b,e=a.split(".");c=c||n;!(e[0]in c)&&c.execScript&&c.execScript("var "+e[0]);for(var h;e.length&&(h=e.shift());)!e.length&&d!==void 0?c[h]=d:c=c[h]?c[h]:c[h]={}},u=function(a){var b=t;function c(){}c.prototype=b.prototype;a.k=b.prototype;a.prototype=new c};var v=/^([\w-]+\.)*([\w-]{2,})(\:[0-9]+)?$/,w=function(a,b){if(!a)return b;var c=a.match(v);return c?c[0]:b};var x,y="false",z=!1,A=x=y=="true"?!0:y=="false"?!1:z;var B=function(){return w("","pubads.g.doubleclick.net")};var C=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var D,E,F,G,H=function(){return n.navigator?n.navigator.userAgent:f};G=F=E=D=!1;var I;if(I=H()){var J=n.navigator;D=I.indexOf("Opera")==0;E=!D&&I.indexOf("MSIE")!=-1;F=!D&&I.indexOf("WebKit")!=-1;G=!D&&!F&&J.product=="Gecko"}var K=D,L=E,M=G,N=F,O;
a:{var P="",Q;if(K&&n.opera)var R=n.opera.version,P=typeof R=="function"?R():R;else if(M?Q=/rv\:([^\);]+)(\)|;)/:L?Q=/MSIE\s+([^\);]+)(\)|;)/:N&&(Q=/WebKit\/(\S+)/),Q)var S=Q.exec(H()),P=S?S[1]:"";if(L){var T,U=n.document;T=U?U.documentMode:void 0;if(T>parseFloat(P)){O=String(T);break a}}O=P}
var aa=O,V={},W=function(a){var b;if(!(b=V[a])){b=V;for(var c=a,d=a,a=aa,e=0,a=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(d).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),h=Math.max(a.length,d.length),j=0;e==0&&j<h;j++){var o=a[j]||"",g=d[j]||"",p=RegExp("(\\d*)(\\D*)","g"),s=RegExp("(\\d*)(\\D*)","g");do{var i=p.exec(o)||["","",""],r=s.exec(g)||["","",""];if(i[0].length==0&&r[0].length==0)break;var e=i[1].length==0?0:parseInt(i[1],10),ba=r[1].length==0?0:parseInt(r[1],10),
e=C(e,ba)||C(i[2].length==0,r[2].length==0)||C(i[2],r[2])}while(e==0)}a=e;b=b[c]=a>=0}return b};!L||W("9");!M&&!L||L&&W("9")||M&&W("1.9.1");L&&W("9");w("","pagead2.googlesyndication.com");var ca=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(f,a[c],c,a)};var X=function(a){this.c=[];this.b={};for(var b=0,c=arguments.length;b<c;++b)this.b[arguments[b]]=""};X.prototype.j=function(a){return this.b.hasOwnProperty(a)?this.b[a]:""};X.prototype.geil=X.prototype.j;var da=function(a){var b=[],c=function(a){a!=""&&b.push(a)};ca(a.b,c);return a.c.length>0&&b.length>0?a.c.join(",")+","+b.join(","):a.c.join(",")+b.join(",")};function ea(a){var b="adsense";if(a&&typeof a=="string"&&a.length>0)if(b==f)a=f;else{var c=window.GS_googleServiceIds_[b];c==f&&(c=b=="adsense"?new Y:new Z,window.GS_googleServiceIds_[b]=c);b:{for(b=0;b<c.a.length;b++)if(a==c.a[b])break b;c.a[c.a.length]=a}a=c}else a=f;return a}q("GS_googleAddAdSenseService",ea);function fa(){for(var a in window.GS_googleServiceIds_){var b=window.GS_googleServiceIds_[a];typeof b!="function"&&b.enable()}}q("GS_googleEnableAllServices",fa);
function ga(){window.GS_googleServiceIds_={}}q("GS_googleResetAllServices",ga);function ha(){var a="adsense",a=a==f?f:window.GS_googleServiceIds_[a];return a=a==f?"":a.a.join()}q("GS_googleGetIdsForAdSenseService",ha);function ia(a){return $(a)}q("GS_googleFindService",ia);function ja(){var a=$("adsense");return a?da(a.g):""}q("GS_googleGetExpIdsForAdSense",ja);function t(a){this.f=a;this.a=[];this.g=new X}
t.prototype.toString=function(){for(var a="["+this.f+" ids: ",b=0;b<this.a.length;b++)b>0&&(a+=","),a+=this.a[b];a+="]";return a};var $=function(a){return a=a==f?f:window.GS_googleServiceIds_[a]};function Z(){t.call(this,"unknown")}u(Z);Z.prototype.enable=function(){};function Y(){t.call(this,"adsense");this.e=!1}u(Y);
Y.prototype.enable=function(){if(!this.e){var a;a=(a=document.URL)&&(a.indexOf("?google_debug")>0||a.indexOf("&google_debug")>0)?"google_ads_dbg.js":"google_ads.js";var b="http://"+w("","partner.googleadservices.com");A&&(b="https://"+w("","securepubads.g.doubleclick.net"));var c="",d;d=B();(d=d=="pubads.g.doubleclick.net")||(c="?prodhost="+B());a=b+"/gampad/"+a+c;b="script";document.write("<"+b+' src="'+a+'"><\/script>');this.e=!0;if(window.GA_jstiming&&
window.GA_jstiming.Timer)window.GA_jstiming.load.name="load",window.GA_jstiming.load.tick("start")}};window.GS_googleServiceIds_||(window.GS_googleServiceIds_={});})()
